package:
  name: narwhals
  version: 1.9.4
  top-level:
    - narwhals
source:
  url: https://files.pythonhosted.org/packages/c4/61/2440cb9ac78164c10d1c1b17a4bbc2ff44e77e42266a3d6876ad2676b807/narwhals-1.9.4-py3-none-any.whl
  sha256: cdd16f73268a3f0d3327aa9e4c6ab25a0b277629d6710bef58e86f40e57e5cc9
about:
  home: https://github.com/narwhals-dev/narwhals
  PyPI: https://pypi.org/project/narwhals
  summary: Extremely lightweight compatibility layer between dataframe libraries
  license: MIT
extra:
  recipe-maintainers:
    - MarcoGorelli
